repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: black
        entry: black aurora/*
        language: python
        types: [python]
        language_version: python3.11

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 aurora/*
        language: python
        types: [python]
        language_version: python3.11
