name: Bug Report
description: File a bug with Aurora.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report!

  - type: textarea
    attributes:
      label: Bug
      description: Provide a description of the bug you have encountered. If you are running into an error, please include the full error message.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.
        This is referred to by community members as creating a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
