name: Welcome

on: [pull_request, issues]

jobs:
  greeting:
    name: 👋 Welcome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for creating an Issue on this repository! 🙌 We will get back to you shortly."
          pr-message: "Thank you for creating an PR on this repository! 🙌 We will get back to you shortly."
