name: Welcome

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  build:
    name: 👋 Welcome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for creating an Issue on this repository! 🙌 We will get back to you shortly."
          pr-message: "Thank you for creating an PR on this repository! 🙌 We will get back to you shortly."
